import {
  ProductWithDetails,
  ProductVariation,
  ProductCategory,
} from "@/lib/types/product";
import { BundleWithDetails, BundleItem, BundleRule } from "@/lib/types/bundle";

// Mock Product Categories (based on your SQL data)
export const mockCategories: ProductCategory[] = [
  {
    id: "cat-1",
    organization_id: "org-1",
    name: "T-Shirt",
    slug: "t-shirt",
    description: "Cotton and custom printed t-shirts",
    sort_order: 1,
    is_active: true,
    is_custom: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "cat-2",
    organization_id: "org-1",
    name: "Polo T-Shirt",
    slug: "polo-t-shirt",
    description: "Collared polo shirts",
    sort_order: 2,
    is_active: true,
    is_custom: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "cat-3",
    organization_id: "org-1",
    name: "Dry-Fit T-Shirt",
    slug: "dry-fit-t-shirt",
    description: "Moisture-wicking athletic shirts",
    sort_order: 3,
    is_active: true,
    is_custom: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "cat-4",
    organization_id: "org-1",
    name: "Umbrella",
    slug: "umbrella",
    description: "Folding and straight umbrellas",
    sort_order: 4,
    is_active: true,
    is_custom: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "cat-5",
    organization_id: "org-1",
    name: "Cup",
    slug: "cup",
    description: "Tumblers, mugs, and drinking vessels",
    sort_order: 5,
    is_active: true,
    is_custom: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "cat-6",
    organization_id: "org-1",
    name: "Lace/Lanyard",
    slug: "lace-lanyard",
    description: "ID lanyards and shoe laces",
    sort_order: 6,
    is_active: true,
    is_custom: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "cat-7",
    organization_id: "org-1",
    name: "Hoodies & Jackets",
    slug: "hoodies-jackets",
    description: "Hooded sweatshirts and jackets",
    sort_order: 7,
    is_active: true,
    is_custom: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "cat-8",
    organization_id: "org-1",
    name: "Accessories",
    slug: "accessories",
    description: "Keychains, pins, and other accessories",
    sort_order: 8,
    is_active: true,
    is_custom: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "cat-9",
    organization_id: "org-1",
    name: "Bags",
    slug: "bags",
    description: "Tote bags, backpacks, and pouches",
    sort_order: 9,
    is_active: true,
    is_custom: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "cat-10",
    organization_id: "org-1",
    name: "Stationery",
    slug: "stationery",
    description: "Notebooks, pens, and school supplies",
    sort_order: 10,
    is_active: true,
    is_custom: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "cat-11",
    organization_id: "org-1",
    name: "Others",
    slug: "others",
    description: "Other merchandise categories",
    sort_order: 11,
    is_active: true,
    is_custom: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
];

// Mock Product Variations
export const mockVariations: ProductVariation[] = [
  // University T-Shirt Variations
  {
    id: "var-1",
    product_id: "prod-1",
    sku: "UNI-TSH-S-BLU",
    attributes: { size: "S", color: "Blue" },
    variation_name: "Small Blue",
    price: 25.99,
    compare_at_price: 29.99,
    stock_quantity: 100,
    reserved_quantity: 5,
    pre_order_quantity: 0,
    completed_orders: 45,
    cancelled_orders: 2,
    available_quantity: 95,
    is_available: true,
    is_archived: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    last_stock_update: "2024-01-15T10:00:00Z",
  },
  {
    id: "var-2",
    product_id: "prod-1",
    sku: "UNI-TSH-M-BLU",
    attributes: { size: "M", color: "Blue" },
    variation_name: "Medium Blue",
    price: 25.99,
    compare_at_price: 29.99,
    stock_quantity: 150,
    reserved_quantity: 8,
    pre_order_quantity: 0,
    completed_orders: 60,
    cancelled_orders: 3,
    available_quantity: 142,
    is_available: true,
    is_archived: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    last_stock_update: "2024-01-15T10:00:00Z",
  },
  {
    id: "var-3",
    product_id: "prod-1",
    sku: "UNI-TSH-L-WHT",
    attributes: { size: "L", color: "White" },
    variation_name: "Large White",
    price: 25.99,
    compare_at_price: 29.99,
    stock_quantity: 80,
    reserved_quantity: 3,
    pre_order_quantity: 0,
    completed_orders: 35,
    cancelled_orders: 1,
    available_quantity: 77,
    is_available: true,
    is_archived: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    last_stock_update: "2024-01-15T10:00:00Z",
  },
  // Coffee Mug Variations
  {
    id: "var-4",
    product_id: "prod-2",
    sku: "MUG-001-WHT",
    attributes: { color: "White", material: "Ceramic" },
    variation_name: "White Ceramic",
    price: 15.99,
    stock_quantity: 200,
    reserved_quantity: 10,
    pre_order_quantity: 0,
    completed_orders: 75,
    cancelled_orders: 5,
    available_quantity: 190,
    is_available: true,
    is_archived: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    last_stock_update: "2024-01-15T10:00:00Z",
  },
  {
    id: "var-5",
    product_id: "prod-2",
    sku: "MUG-001-BLK",
    attributes: { color: "Black", material: "Ceramic" },
    variation_name: "Black Ceramic",
    price: 15.99,
    stock_quantity: 150,
    reserved_quantity: 7,
    pre_order_quantity: 0,
    completed_orders: 45,
    cancelled_orders: 2,
    available_quantity: 143,
    is_available: true,
    is_archived: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    last_stock_update: "2024-01-15T10:00:00Z",
  },
  // Hoodie Variations
  {
    id: "var-6",
    product_id: "prod-3",
    sku: "HOD-001-M-GRY",
    attributes: { size: "M", color: "Gray" },
    variation_name: "Medium Gray",
    price: 49.99,
    compare_at_price: 59.99,
    stock_quantity: 50,
    reserved_quantity: 2,
    pre_order_quantity: 0,
    completed_orders: 20,
    cancelled_orders: 1,
    available_quantity: 48,
    is_available: true,
    is_archived: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    last_stock_update: "2024-01-15T10:00:00Z",
  },
  // Umbrella Variations
  {
    id: "var-7",
    product_id: "prod-4",
    sku: "UMB-001-BLK",
    attributes: { color: "Black", type: "Folding" },
    variation_name: "Black Folding",
    price: 22.99,
    stock_quantity: 75,
    reserved_quantity: 5,
    pre_order_quantity: 0,
    completed_orders: 30,
    cancelled_orders: 2,
    available_quantity: 70,
    is_available: true,
    is_archived: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    last_stock_update: "2024-01-15T10:00:00Z",
  },
];

// Mock Products
export const mockProducts: ProductWithDetails[] = [
  {
    id: "prod-1",
    account_id: "user-1",
    organization_id: "org-1",
    name: "University Logo T-Shirt",
    status: "published",
    description:
      "Premium cotton t-shirt with university logo print. Available in multiple sizes and colors.",
    search_keywords: ["university", "t-shirt", "logo", "cotton", "casual"],
    is_approved: true,
    total_sales: 3500,
    total_orders: 140,
    is_discounted: true,
    discount_type: "percentage",
    discount_target: "all",
    discount_value: 13.3,
    featured_photo_url: "/placeholder-img.jpg",
    photo_urls: ["/placeholder-img.jpg", "/placeholder-img.jpg"],
    can_pre_order: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    is_archived: false,
    category_id: "cat-1",
    variations: [
      mockVariations.find((v) => v.id === "var-1")!,
      mockVariations.find((v) => v.id === "var-2")!,
      mockVariations.find((v) => v.id === "var-3")!,
    ],
    category: mockCategories.find((c) => c.id === "cat-1"),
  },
  {
    id: "prod-2",
    account_id: "user-1",
    organization_id: "org-1",
    name: "Custom Coffee Mug",
    status: "published",
    description:
      "Personalized ceramic coffee mug perfect for daily use or as a gift.",
    search_keywords: ["coffee", "mug", "ceramic", "custom", "gift"],
    is_approved: true,
    total_sales: 1200,
    total_orders: 120,
    is_discounted: false,
    discount_type: "none",
    discount_value: 0,
    featured_photo_url: "/placeholder-img.jpg",
    photo_urls: ["/placeholder-img.jpg"],
    can_pre_order: false,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    is_archived: false,
    category_id: "cat-5",
    variations: [
      mockVariations.find((v) => v.id === "var-4")!,
      mockVariations.find((v) => v.id === "var-5")!,
    ],
    category: mockCategories.find((c) => c.id === "cat-5"),
  },
  {
    id: "prod-3",
    account_id: "user-1",
    organization_id: "org-1",
    name: "Premium University Hoodie",
    status: "published",
    description:
      "Comfortable hoodie with university branding. Perfect for cooler weather.",
    search_keywords: ["hoodie", "university", "warm", "casual", "winter"],
    is_approved: true,
    total_sales: 1000,
    total_orders: 20,
    is_discounted: true,
    discount_type: "fixed_amount",
    discount_target: "all",
    discount_value: 10,
    featured_photo_url: "/placeholder-img.jpg",
    photo_urls: ["/placeholder-img.jpg", "/placeholder-img.jpg"],
    can_pre_order: false,
    created_at: "2024-01-14T10:00:00Z",
    updated_at: "2024-01-14T10:00:00Z",
    is_archived: false,
    category_id: "cat-7",
    variations: [mockVariations.find((v) => v.id === "var-6")!],
    category: mockCategories.find((c) => c.id === "cat-7"),
  },
  {
    id: "prod-4",
    account_id: "user-1",
    organization_id: "org-1",
    name: "Compact Travel Umbrella",
    status: "published",
    description:
      "Lightweight and durable folding umbrella with university branding.",
    search_keywords: ["umbrella", "travel", "compact", "rain", "weather"],
    is_approved: true,
    total_sales: 690,
    total_orders: 30,
    is_discounted: false,
    discount_type: "none",
    discount_value: 0,
    featured_photo_url: "/placeholder-img.jpg",
    photo_urls: ["/placeholder-img.jpg"],
    can_pre_order: false,
    created_at: "2024-01-13T10:00:00Z",
    updated_at: "2024-01-13T10:00:00Z",
    is_archived: false,
    category_id: "cat-4",
    variations: [mockVariations.find((v) => v.id === "var-7")!],
    category: mockCategories.find((c) => c.id === "cat-4"),
  },
  {
    id: "prod-5",
    account_id: "user-1",
    organization_id: "org-1",
    name: "Student Notebook Set",
    status: "draft",
    description: "High-quality notebook set with university logo for students.",
    search_keywords: [
      "notebook",
      "student",
      "stationery",
      "study",
      "university",
    ],
    is_approved: false,
    total_sales: 0,
    total_orders: 0,
    is_discounted: false,
    discount_type: "none",
    discount_value: 0,
    featured_photo_url: "/placeholder-img.jpg",
    photo_urls: ["/placeholder-img.jpg"],
    can_pre_order: true,
    created_at: "2024-01-16T10:00:00Z",
    updated_at: "2024-01-16T10:00:00Z",
    is_archived: false,
    category_id: "cat-10",
    category: mockCategories.find((c) => c.id === "cat-10"),
  },
];

// Mock Bundle Items
export const mockBundleItems: BundleItem[] = [
  {
    id: "item-1",
    bundle_id: "bundle-1",
    product_id: "prod-1",
    variation_id: "var-2",
    quantity: 1,
    is_required: true,
    can_choose_variation: true,
    default_variation_id: "var-2",
    apply_bundle_discount: true,
    sort_order: 1,
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "item-2",
    bundle_id: "bundle-1",
    product_id: "prod-2",
    variation_id: "var-4",
    quantity: 1,
    is_required: true,
    can_choose_variation: true,
    default_variation_id: "var-4",
    apply_bundle_discount: true,
    sort_order: 2,
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "item-3",
    bundle_id: "bundle-2",
    product_id: "prod-3",
    variation_id: "var-6",
    quantity: 1,
    is_required: true,
    can_choose_variation: false,
    default_variation_id: "var-6",
    apply_bundle_discount: true,
    sort_order: 1,
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "item-4",
    bundle_id: "bundle-2",
    product_id: "prod-1",
    variation_id: "var-1",
    quantity: 2,
    is_required: false,
    can_choose_variation: true,
    default_variation_id: "var-1",
    apply_bundle_discount: true,
    custom_discount_percentage: 20,
    sort_order: 2,
    created_at: "2024-01-15T10:00:00Z",
  },
];

// Mock Bundle Rules
export const mockBundleRules: BundleRule[] = [
  {
    id: "rule-1",
    bundle_id: "bundle-1",
    rule_type: "minimum_quantity",
    rule_operator: "require",
    rule_value: { min_items: 2 },
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "rule-2",
    bundle_id: "bundle-2",
    rule_type: "category_discount",
    rule_operator: "include",
    rule_value: { category_ids: ["cat-1", "cat-7"], extra_discount: 5 },
    created_at: "2024-01-15T10:00:00Z",
  },
];

// Mock Product Bundles
export const mockBundles: BundleWithDetails[] = [
  {
    id: "bundle-1",
    name: "Student Starter Pack",
    organization_id: "org-1",
    description: "Perfect bundle for new students - includes t-shirt and mug",
    bundle_type: "static",
    base_price: 41.98,
    bundle_price: 35.99,
    discount_percentage: 14.3,
    manage_bundle_stock: false,
    bundle_stock_quantity: 0,
    min_quantity: 1,
    max_quantity: 5,
    is_active: true,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    items: [
      mockBundleItems.find((i) => i.id === "item-1")!,
      mockBundleItems.find((i) => i.id === "item-2")!,
    ],
    rules: [mockBundleRules.find((r) => r.id === "rule-1")!],
  },
  {
    id: "bundle-2",
    name: "Winter Campus Bundle",
    organization_id: "org-1",
    description: "Stay warm with our hoodie and t-shirt combo",
    bundle_type: "dynamic",
    base_price: 101.97,
    bundle_price: 85.99,
    discount_percentage: 15.7,
    manage_bundle_stock: true,
    bundle_stock_quantity: 25,
    min_quantity: 1,
    max_quantity: 3,
    is_active: true,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    items: [
      mockBundleItems.find((i) => i.id === "item-3")!,
      mockBundleItems.find((i) => i.id === "item-4")!,
    ],
    rules: [mockBundleRules.find((r) => r.id === "rule-2")!],
  },
];

// Helper function to get product by ID
export const getProductById = (id: string): ProductWithDetails | undefined => {
  return mockProducts.find((product) => product.id === id);
};

// Helper function to get products by category
export const getProductsByCategory = (
  categoryId: string
): ProductWithDetails[] => {
  return mockProducts.filter((product) => product.category_id === categoryId);
};

// Helper function to get bundle by ID
export const getBundleById = (id: string): BundleWithDetails | undefined => {
  return mockBundles.find((bundle) => bundle.id === id);
};

// Helper function to get published products
export const getPublishedProducts = (): ProductWithDetails[] => {
  return mockProducts.filter((product) => product.status === "published");
};

// Helper function to get active bundles
export const getActiveBundles = (): BundleWithDetails[] => {
  return mockBundles.filter((bundle) => bundle.is_active);
};
